/**
 * Notification Service for Public Pulse
 * Handles Email and SMS notifications for alerts
 */

import nodemailer from 'nodemailer';

export interface AlertPayload {
    id: string;
    title: string;
    message: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    area_name?: string;
    prediction_type?: string;
    probability?: number;
}

// Email configuration
const emailTransporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.SMTP_USER || 'asrajput5656@gmail.com',
        pass: process.env.SMTP_PASS || ''
    }
});

// Severity colors for email
const severityColors: Record<string, string> = {
    low: '#10B981',
    medium: '#F59E0B',
    high: '#EF4444',
    critical: '#7C3AED'
};

/**
 * Send an email alert
 */
export async function sendEmailAlert(alert: AlertPayload, to: string): Promise<boolean> {
    // Skip if no SMTP configured
    if (!process.env.SMTP_USER) {
        console.log('[Notification] Email skipped - SMTP not configured');
        console.log(`[Notification] Would send email to ${to}: ${alert.title}`);
        return true;
    }

    const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: ${severityColors[alert.severity]}; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
                <h1 style="margin: 0; font-size: 24px;">⚠️ ${alert.title}</h1>
                <p style="margin: 5px 0 0 0; opacity: 0.9;">Severity: ${alert.severity.toUpperCase()}</p>
            </div>
            <div style="background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
                <p style="font-size: 16px; color: #374151; line-height: 1.6;">${alert.message}</p>
                ${alert.area_name ? `<p style="color: #6b7280; margin-top: 10px;"><strong>Location:</strong> ${alert.area_name}</p>` : ''}
                ${alert.probability ? `<p style="color: #6b7280;"><strong>Risk Level:</strong> ${(alert.probability * 100).toFixed(0)}%</p>` : ''}
                <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
                <p style="color: #9ca3af; font-size: 12px;">
                    This alert was generated by Public Pulse - Vadodara Civic Intelligence Platform<br>
                    Alert ID: ${alert.id}
                </p>
            </div>
        </div>
    `;

    try {
        await emailTransporter.sendMail({
            from: process.env.SMTP_FROM || 'alerts@publicpulse.gov.in',
            to,
            subject: `[${alert.severity.toUpperCase()}] ${alert.title}`,
            html
        });
        console.log(`[Notification] Email sent to ${to}`);
        return true;
    } catch (error) {
        console.error('[Notification] Email failed:', error);
        return false;
    }
}

/**
 * Send an SMS alert (Twilio integration placeholder)
 */
export async function sendSMSAlert(alert: AlertPayload, to: string): Promise<boolean> {
    // Skip if no Twilio configured
    if (!process.env.TWILIO_ACCOUNT_SID) {
        console.log('[Notification] SMS skipped - Twilio not configured');
        console.log(`[Notification] Would send SMS to ${to}: ${alert.title}`);
        return true;
    }

    const message = `[${alert.severity.toUpperCase()}] ${alert.title}\n${alert.message}\n- Public Pulse Vadodara`;

    try {
        // Twilio integration would go here
        // const client = require('twilio')(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN);
        // await client.messages.create({
        //     body: message,
        //     from: process.env.TWILIO_PHONE,
        //     to: to
        // });
        console.log(`[Notification] SMS would be sent to ${to}: ${message.substring(0, 50)}...`);
        return true;
    } catch (error) {
        console.error('[Notification] SMS failed:', error);
        return false;
    }
}

/**
 * Send a WhatsApp alert using Twilio
 */
export async function sendWhatsAppAlert(alert: AlertPayload, to: string): Promise<boolean> {
    const accountSid = process.env.TWILIO_ACCOUNT_SID || '';
    const authToken = process.env.TWILIO_AUTH_TOKEN || '';
    const fromNumber = process.env.TWILIO_WHATSAPP_FROM || 'whatsapp:+14155238886';

    if (!authToken) {
        console.log('[Notification] WhatsApp skipped - Twilio Auth Token missing');
        return false;
    }

    try {
        // Dynamic import to avoid build errors if twilio not installed
        const twilio = require('twilio');
        const client = twilio(accountSid, authToken);

        const message = await client.messages.create({
            from: fromNumber,
            body: `🚨 *${alert.title}*\n\n${alert.message}\n\n📍 ${alert.area_name || 'Vadodara'}\n⚠️ Severity: ${alert.severity.toUpperCase()}`,
            to: to.startsWith('whatsapp:') ? to : `whatsapp:${to}`
        });

        console.log(`[Notification] WhatsApp sent to ${to}. SID: ${message.sid}`);
        return true;
    } catch (error: any) {
        console.error('[Notification] WhatsApp failed:', error.message);
        return false;
    }
}

/**
 * Send alert to multiple channels
 */
export async function sendMultiChannelAlert(
    alert: AlertPayload,
    channels: { email?: string; sms?: string; whatsapp?: string }
): Promise<{ email: boolean; sms: boolean; whatsapp: boolean }> {
    const results = {
        email: channels.email ? await sendEmailAlert(alert, channels.email) : true,
        sms: channels.sms ? await sendSMSAlert(alert, channels.sms) : true,
        whatsapp: channels.whatsapp ? await sendWhatsAppAlert(alert, channels.whatsapp) : true
    };
    return results;
}

